name: Build Snapshots
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
permissions:
  contents: write
jobs:
  build:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Get short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
      - name: Build Package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :overflow-core-all:shadowJar
        env:
          # 加上 VERSION_OVERRIDE 将会设为 -SNAPSHOT 版本
          ORG_GRADLE_PROJECT_VERSION_OVERRIDE: ${{ env.SHORT_SHA }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: overflow-core-all-${{ env.SHORT_SHA }}
          path: overflow-core-all/build/libs/*-all.jar
          if-no-files-found: error
